name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the site in the jekyll/builder container
      run: |
            docker run \
              -v ${{ github.workspace }}:/srv/jekyll \
              jekyll/builder:4.2.0 \
              /bin/bash -c 'chmod 777 /srv/jekyll && bundle exec jekyll build --future'

    - name: Deploy website
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./_site/
